In [21]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
x = pd.read_excel("C:\\Users\\post2\\OneDrive\\Documents\\Random datasets\\Cyber crime in India since 2003\\All years datasets\\output2003.xlsx")
df = pd.DataFrame(x)

df

,Evaluation Only. Created with Aspose.PDF. Copyright 2002-2023 Aspose Pty Ltd.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,TABLE-18.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Incidence Of Cases Registered Under Cyber Crim...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,and Percentage Variation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SL.No,State/UT,NaN,IT ACT,NaN,NaN,IPC Section,NaN
4,NaN,NaN,2002.0,2003,Variation,2002.0,2003,Variation
5,1,2,3.0,4,5,6.0,7,8
6,1,ANDHRA PRADESH,8.0,3,-62.50,253.0,218,-13.83
7,2,ARUNACHAL PRADESH,0.0,0,-,0.0,0,-
8,3,ASSAM,2.0,0,-100.00,0.0,0,-
9,4,BIHAR,0.0,0,-,0.0,0,-
10,5,CHHATTISGARH,0.0,0,-,0.0,0,-
11,6,GOA,4.0,2,-50.00,4.0,0,-100.00
12,7,GUJARAT,1.0,14,1300,249.0,15,-93.98
13,8,HARYANA,2.0,0,-100.00,0.0,1,-
14,9,HIMACHAL PRADESH,0.0,0,-,99.0,87,-12.12
15,10,JAMMU & KASHMIR,1.0,0,-100.00,0.0,0,-
16,11,JHARKHAND,0.0,0,-,0.0,0,-
17,12,KARNATAKA,15.0,7,-53.33,0.0,1,-
18,13,KERALA,3.0,1,-66.67,1.0,0,-100.00
19,14,MADHYA PRADESH,0.0,0,-,0.0,0,-
20,15,MAHARASHTRA,12.0,12,0,1.0,5,400
21,16,MANIPUR,0.0,0,-,0.0,0,-
22,17,MEGHALAYA,0.0,0,-,0.0,0,-
23,18,MIZORAM,0.0,0,-,0.0,0,-
24,19,NAGALAND,0.0,0,-,0.0,0,-
25,20,ORISSA,4.0,1,-75.00,0.0,4,-
26,21,PUNJAB,3.0,2,-33.33,26.0,61,134.62
27,22,RAJASTHAN,0.0,0,-,0.0,0,-
28,23,SIKKIM,0.0,0,-,0.0,0,-
29,24,TAMIL NADU,3.0,10,233.33,0.0,0,-
30,25,TRIPURA,0.0,0,-,0.0,0,-
31,26,UTTAR PRADESH,5.0,2,-60.00,81.0,3,-96.30
32,27,UTTRANCHAL,0.0,1,-,0.0,0,-
33,28,WEST BENGAL,0.0,0,-,0.0,0,-
34,NaN,TOTAL (STATES),63.0,55,-12.70,714.0,395,-44.68
35,29,A & N ISLANDS,0.0,0,-,15.0,16,6.67
36,30,CHANDIGARH,2.0,1,-50.0,0.0,0,-
37,31,D & N HAVELI,0.0,0,-,0.0,0,-
38,32,DAMAN & DIU,0.0,NaN,-,7.0,NaN,-
39,33,DELHI,5.0,4,-20.00,2.0,0,-100.00
40,34,LAKSHADWEEP,0.0,0,-,0.0,0,-
41,35,PONDICHERRY,0.0,0,-,0.0,0,-
42,NaN,TOTAL (UTS),7.0,5,-28.57,24.0,16,-33.33
43,NaN,TOTAL (ALL INDIA),70.0,60,-14.28,738.0,411,-44.31
44,NA STANDS FOR NOT AVAILABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df=df.drop(["Evaluation Only. Created with Aspose.PDF. Copyright 2002-2023 Aspose Pty Ltd."],axis=1)
df

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,State/UT,NaN,IT ACT,NaN,NaN,IPC Section,NaN
4,NaN,2002.0,2003,Variation,2002.0,2003,Variation
5,2,3.0,4,5,6.0,7,8
6,ANDHRA PRADESH,8.0,3,-62.50,253.0,218,-13.83
7,ARUNACHAL PRADESH,0.0,0,-,0.0,0,-
8,ASSAM,2.0,0,-100.00,0.0,0,-
9,BIHAR,0.0,0,-,0.0,0,-
10,CHHATTISGARH,0.0,0,-,0.0,0,-
11,GOA,4.0,2,-50.00,4.0,0,-100.00
12,GUJARAT,1.0,14,1300,249.0,15,-93.98
13,HARYANA,2.0,0,-100.00,0.0,1,-
14,HIMACHAL PRADESH,0.0,0,-,99.0,87,-12.12
15,JAMMU & KASHMIR,1.0,0,-100.00,0.0,0,-
16,JHARKHAND,0.0,0,-,0.0,0,-
17,KARNATAKA,15.0,7,-53.33,0.0,1,-
18,KERALA,3.0,1,-66.67,1.0,0,-100.00
19,MADHYA PRADESH,0.0,0,-,0.0,0,-
20,MAHARASHTRA,12.0,12,0,1.0,5,400
21,MANIPUR,0.0,0,-,0.0,0,-
22,MEGHALAYA,0.0,0,-,0.0,0,-
23,MIZORAM,0.0,0,-,0.0,0,-
24,NAGALAND,0.0,0,-,0.0,0,-
25,ORISSA,4.0,1,-75.00,0.0,4,-
26,PUNJAB,3.0,2,-33.33,26.0,61,134.62
27,RAJASTHAN,0.0,0,-,0.0,0,-
28,SIKKIM,0.0,0,-,0.0,0,-
29,TAMIL NADU,3.0,10,233.33,0.0,0,-
30,TRIPURA,0.0,0,-,0.0,0,-
31,UTTAR PRADESH,5.0,2,-60.00,81.0,3,-96.30
32,UTTRANCHAL,0.0,1,-,0.0,0,-
33,WEST BENGAL,0.0,0,-,0.0,0,-
34,TOTAL (STATES),63.0,55,-12.70,714.0,395,-44.68
35,A & N ISLANDS,0.0,0,-,15.0,16,6.67
36,CHANDIGARH,2.0,1,-50.0,0.0,0,-
37,D & N HAVELI,0.0,0,-,0.0,0,-
38,DAMAN & DIU,0.0,NaN,-,7.0,NaN,-
39,DELHI,5.0,4,-20.00,2.0,0,-100.00
40,LAKSHADWEEP,0.0,0,-,0.0,0,-
41,PONDICHERRY,0.0,0,-,0.0,0,-
42,TOTAL (UTS),7.0,5,-28.57,24.0,16,-33.33
43,TOTAL (ALL INDIA),70.0,60,-14.28,738.0,411,-44.31
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df=df.iloc[6:44,:]
df

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
6,ANDHRA PRADESH,8.0,3,-62.50,253.0,218,-13.83
7,ARUNACHAL PRADESH,0.0,0,-,0.0,0,-
8,ASSAM,2.0,0,-100.00,0.0,0,-
9,BIHAR,0.0,0,-,0.0,0,-
10,CHHATTISGARH,0.0,0,-,0.0,0,-
11,GOA,4.0,2,-50.00,4.0,0,-100.00
12,GUJARAT,1.0,14,1300,249.0,15,-93.98
13,HARYANA,2.0,0,-100.00,0.0,1,-
14,HIMACHAL PRADESH,0.0,0,-,99.0,87,-12.12
15,JAMMU & KASHMIR,1.0,0,-100.00,0.0,0,-
16,JHARKHAND,0.0,0,-,0.0,0,-
17,KARNATAKA,15.0,7,-53.33,0.0,1,-
18,KERALA,3.0,1,-66.67,1.0,0,-100.00
19,MADHYA PRADESH,0.0,0,-,0.0,0,-
20,MAHARASHTRA,12.0,12,0,1.0,5,400
21,MANIPUR,0.0,0,-,0.0,0,-
22,MEGHALAYA,0.0,0,-,0.0,0,-
23,MIZORAM,0.0,0,-,0.0,0,-
24,NAGALAND,0.0,0,-,0.0,0,-
25,ORISSA,4.0,1,-75.00,0.0,4,-
26,PUNJAB,3.0,2,-33.33,26.0,61,134.62
27,RAJASTHAN,0.0,0,-,0.0,0,-
28,SIKKIM,0.0,0,-,0.0,0,-
29,TAMIL NADU,3.0,10,233.33,0.0,0,-
30,TRIPURA,0.0,0,-,0.0,0,-
31,UTTAR PRADESH,5.0,2,-60.00,81.0,3,-96.30
32,UTTRANCHAL,0.0,1,-,0.0,0,-
33,WEST BENGAL,0.0,0,-,0.0,0,-
34,TOTAL (STATES),63.0,55,-12.70,714.0,395,-44.68
35,A & N ISLANDS,0.0,0,-,15.0,16,6.67
36,CHANDIGARH,2.0,1,-50.0,0.0,0,-
37,D & N HAVELI,0.0,0,-,0.0,0,-
38,DAMAN & DIU,0.0,NaN,-,7.0,NaN,-
39,DELHI,5.0,4,-20.00,2.0,0,-100.00
40,LAKSHADWEEP,0.0,0,-,0.0,0,-
41,PONDICHERRY,0.0,0,-,0.0,0,-
42,TOTAL (UTS),7.0,5,-28.57,24.0,16,-33.33
43,TOTAL (ALL INDIA),70.0,60,-14.28,738.0,411,-44.31

In [25]:
col_ind=["State/UT","2002","2003","Variation","2002","2003","Variation"]
df=df.set_axis(col_ind,axis=1)
df=df.set_axis(np.arange(1,df.shape[0]+1,1),axis=0)
df

              State/UT  2002 2003 Variation   2002 2003 Variation
1       ANDHRA PRADESH   8.0    3    -62.50  253.0  218    -13.83
2    ARUNACHAL PRADESH   0.0    0         -    0.0    0         -
3                ASSAM   2.0    0   -100.00    0.0    0         -
4                BIHAR   0.0    0         -    0.0    0         -
5         CHHATTISGARH   0.0    0         -    0.0    0         -
6                  GOA   4.0    2    -50.00    4.0    0   -100.00
7              GUJARAT   1.0   14      1300  249.0   15    -93.98
8              HARYANA   2.0    0   -100.00    0.0    1         -
9     HIMACHAL PRADESH   0.0    0         -   99.0   87    -12.12
10    JAMMU & KASHMIR    1.0    0  -100.00     0.0    0        -
11           JHARKHAND   0.0    0         -    0.0    0         -
12           KARNATAKA  15.0    7    -53.33    0.0    1         -
13              KERALA   3.0    1    -66.67    1.0    0   -100.00
14      MADHYA PRADESH   0.0    0         -    0.0    0         -
15         MAHARASHTRA  12.0   12         0    1.0    5       400
16             MANIPUR   0.0    0         -    0.0    0         -
17           MEGHALAYA   0.0    0         -    0.0    0         -
18             MIZORAM   0.0    0         -    0.0    0         -
19            NAGALAND   0.0    0         -    0.0    0         -
20              ORISSA   4.0    1    -75.00    0.0    4         -
21              PUNJAB   3.0    2    -33.33   26.0   61    134.62
22           RAJASTHAN   0.0    0         -    0.0    0         -
23              SIKKIM   0.0    0         -    0.0    0         -
24          TAMIL NADU   3.0   10    233.33    0.0    0         -
25             TRIPURA   0.0    0         -    0.0    0         -
26       UTTAR PRADESH   5.0    2    -60.00   81.0    3    -96.30
27          UTTRANCHAL   0.0    1         -    0.0    0         -
28         WEST BENGAL   0.0    0         -    0.0    0         -
29      TOTAL (STATES)  63.0   55    -12.70  714.0  395    -44.68
30       A & N ISLANDS   0.0    0        -    15.0   16      6.67
31          CHANDIGARH   2.0    1     -50.0    0.0    0         -
32        D & N HAVELI   0.0    0        -     0.0    0        -
33         DAMAN & DIU   0.0  NaN         -    7.0  NaN         -
34               DELHI   5.0    4    -20.00    2.0    0   -100.00
35         LAKSHADWEEP   0.0    0         -    0.0    0         -
36         PONDICHERRY   0.0    0         -    0.0    0         -
37         TOTAL (UTS)   7.0    5    -28.57   24.0   16    -33.33
38  TOTAL (ALL INDIA)   70.0   60   -14.28   738.0  411   -44.31

In [26]:
df.to_csv("Attacks in 2003.csv")